MediatoriV2/Controllers/UtentiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyManagerCSharp;


using System.Diagnostics;


namespace mediatori.Controllers
{
    public class UtentiController : MyBaseController
    {
        private MyUsers.UserManager manager = null;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);

            if (db != null)
            {
                manager = new MyUsers.UserManager(db.Database.Connection);
            }
        }

        public ActionResult Index(MyUsers.Models.SearchUsers model)
        {
            if (model.Sort == "Login")
            {
                model.Sort = "my_login";
            }
            else if (model.Sort == "DateAdded")
            {
                model.Sort = "date_added";
            }
            else if (model.Sort == "DateLastLogin")
            {
                model.Sort = "date_last_login";
            }
            else if (model.Sort == "isEnabled")
            {
                model.Sort = "is_enabled";
            }
            TryUpdateModel(model.filter, "filter");

            Debug.WriteLine(String.Format("Filtri di ricerca  Nome: {0} Email: {1}", model.filter.nome, model.filter.email));


            manager.openConnection();
            try
            {
                manager.getList(model);

                //Aggiungo il profilo !!
                MyUsers.Models.MyUser toBeRemoved = null;

                foreach (MyUsers.Models.MyUser u in model.Utenti)
                {
                    if (u.login.StartsWith("admin@"))
                    {
                        //lo nascondo
                        toBeRemoved = u;
                    }
                    else
                    {
                        manager.setProfili(u);
                        manager.setGroups(u);
                    }
                }

                if (toBeRemoved != null)
                {
                    model.Utenti.Remove(toBeRemoved);
                    model.TotalRows = model.TotalRows - 1;
                }

            }
            finally
            {
                manager.closeConnection();
            }

            return View(model);
        }

        public ActionResult Details(long id = 0)
        {
            Models.MyUserModel model = new Models.MyUserModel();
            manager.openConnection();
            try
            {
                model.Utente = manager.getUser(id);

                if (model.Utente == null)
                {
                    return HttpNotFound();
                }

                manager.setProfili(model.Utente);
                manager.setGroups(model.Utente);
                //manager.setRoles(model.Utente);

                //                MyUsers.CustomerManager c = new MyUsers.CustomerManager(manager.getConnection());
                //              c.set(model.Utente);


                //REPORTS
                // MyManagerCSharp.RGraph.Models.RGraphModel report;
                //MyUsers.Reports.ReportsUsers reportManager = new MyUsers.Reports.ReportsUsers(manager.getConnection());



            }
            finally
            {
                manager.closeConnection();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddProfilo(long? userId)
        {
            if (userId == null)
            {
                throw new ArgumentNullException("userId");
            }

            Debug.WriteLine("UserId: " + userId);
            Debug.WriteLine("ProfiliIDs: " + Request["profiliIDs"]);

            manager.openConnection();
            try
            {

                List<MyUsers.Models.MyProfile> lista = new List<MyUsers.Models.MyProfile>();

                foreach (string id in Request["profiliIDs"].Split(','))
                {
                    Debug.WriteLine("Profile: " + id);
                    lista.Add(new MyUsers.Models.MyProfile(id));
                }
                manager.updateProfili(lista, (long)userId);


            }
            finally
            {
                manager.closeConnection();
            }


            return RedirectToAction("Details", new { id = userId });

            //return new RedirectResult(Url.Action("Details", new { id = userId }) + "#tabs-3");
        }

        public ActionResult Register()
        {
            Models.RegisterModel model = new Models.RegisterModel();

            model.ProfiliDisponibili = manager.getProfili();
            model.UserName = "";
            model.Password = "";
            model.ConfirmPassword = "";


            //model.roles 

            return View(model);
        }

        [HttpPost]
        //[Authorize(Roles = "Amministratore")]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Models.RegisterModel model)
        {

            if (!ModelState.IsValid)
            {
                var message = string.Join(" | ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Failed, "Impossibile salvare l'utente, verificare i dati: " + Environment.NewLine + message);

                model.ProfiliDisponibili = manager.getProfili();
                // model.Password = "";
                model.ConfirmPassword = "";

                return View(model);
            }



            if (ModelState.IsValid)
            {
                MyUsers.Models.MyUser u = new MyUsers.Models.MyUser();
                u.login = model.UserName.Trim();
                u.password = model.Password.Trim();
                u.isEnabled = true;


                bool esito;
                esito = MyManagerCSharp.RegularExpressionManager.isValidEmail(u.login);
                if (esito == false)
                {
                    string messaggio;
                    messaggio = "Inserire un indirizzo email valido.";
                    TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Failed, messaggio);
                    // ModelState.AddModelError("", messaggio);
                    model.ProfiliDisponibili = manager.getProfili();
                    return View(model);
                }

                string dominio;
                dominio = u.login.Split('@')[1];

                if ((Session["MySessionData"] as SessionData).Dominio != dominio)
                {
                    string messaggio;
                    messaggio = "L'email dell'utente deve appartenere al dominio: @" + (Session["MySessionData"] as SessionData).Dominio;
                    TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Failed, messaggio);
                    // ModelState.AddModelError("", messaggio);
                    model.ProfiliDisponibili = manager.getProfili();
                    return View(model);

                }



                long userId;
                try
                {
                    manager.openConnection();

                    userId = manager.getUserIdFromLogin(u.login);
                    if (userId != -1)
                    {
                        TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Failed, "Spiacenti, risulta già presente un utente registrato con questo indizzo email.");
                        model.ProfiliDisponibili = manager.getProfili();
                        return View(model);
                    }

                    //Rel. 1.0.0.8
                    u.email = u.login;

                    userId = manager.insert(u);

                    if (userId != -1)
                    {
                        /*** PROFILI **/
                        Debug.WriteLine("Profili: " + Request.Form["roles"]);
                        List<MyUsers.Models.MyProfile> lista = new List<MyUsers.Models.MyProfile>();
                        foreach (string id in Request["roles"].Split(','))
                        {
                            Debug.WriteLine("Profile: " + id);
                            lista.Add(new MyUsers.Models.MyProfile(id));
                        }
                        manager.updateProfili(lista, (long)userId);
                    }
                }
                finally
                {
                    manager.closeConnection();
                }

                TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Success, "Registrazione utente " + u.login + " conclusa con successo");
                return RedirectToAction("Index");
            }


            model.ProfiliDisponibili = manager.getProfili();
            // model.Password = "";
            model.ConfirmPassword = "";

            return View(model);
        }


        public ActionResult Delete(long id = 0)
        {
            MyUsers.Models.MyUser myuser = null;

            manager.openConnection();
            try
            {
                myuser = manager.getUser(id);


                if (myuser == null)
                {
                    return HttpNotFound();
                }

                int check = db.Segnalazioni.Where(p => p.utenteInserimento == myuser.login).Count();
                if (check > 0)
                {
                    TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Exception, "Attenzione! Non è possibile eliminare " + myuser.login + " poichè ci sono segnalazioni associate");
                }
                check = db.Pratiche.Where(p => p.utenteInserimento == myuser.login).Count();
                if (check > 0)
                {
                    TempData["Message"] = new MyMessage(MyMessage.MyMessageType.Exception, "Attenzione! Non è possibile eliminare " + myuser.login + " poichè ci sono pratiche associate");
                }

            }

            finally
            {

MediatoriV2/Views/Utenti/Delete.cshtml
@model MyUsers.Models.MyUser

@{
    ViewBag.Title = "Delete utente:" + ((String.IsNullOrEmpty(Model.login)) ? "N/A" : Model.login);
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
    }

<h2>Cancellazione utente: @Model.login (id: @Model.userId)</h2>

<h3>Confermare la cancellazione di questo utente?</h3>


<h3>Account</h3>
@{Html.RenderPartial("~/Areas/Admin/Views/Users/TabInfoAccount.cshtml", Model);}





@using (Html.BeginForm("Delete", "Utenti", FormMethod.Post, new { id = "MyForm" }))
{
    @Html.AntiForgeryToken()

    <input  type="hidden" name="id" value="@Model.userId" />
    
    <div data-role="controlgrup" data-type="horizontal">
        <a href="@Url.Action("Index", "Utenti")" class="ui-btn-inline ui-btn ui-corner-all ui-mini" >Torna alla lista</a>
        <a href="@Url.Action("Details", "Utenti", new { id = Model.userId })"  class="ui-btn-inline ui-btn ui-corner-all ui-mini" >Annulla</a>
        <input type="submit" value="Elimina" data-inline="true" data-mini="true" data-icon="delete" />
    </div>
}

MediatoriV2/Views/Utenti/Details.cshtml
@model mediatori.Models.MyUserModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

<h2>Utente: @Model.Utente.login</h2>

<div class="ui-grid-a">
    <div class="ui-block-a">
        <div class="ui-bar ui-bar-b">Login:</div>
        <div class="ui-bar ui-bar-b">Profilo:</div>
        <div class="ui-bar ui-bar-b">Stato:</div>
        <div class="ui-bar ui-bar-b">Email:</div>
        <div class="ui-bar ui-bar-b">Data inserimento:</div>
        <div class="ui-bar ui-bar-b">Login success:</div>
        <div class="ui-bar ui-bar-b">Login failed:</div>
        <div class="ui-bar ui-bar-b">Data ultimo accesso:</div>
    </div>
    <div class="ui-block-b">
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.Utente.login)</div>
        <div class="ui-bar ui-body-a">@(Model.Utente.Profili == null || Model.Utente.Profili.Count == 0 ? "N/A" : Model.Utente.Profili[0].nome)</div>
        <div class="ui-bar ui-body-a">@(Model.Utente.isEnabled == null?"N/A":MyHelper.decodeAttivo((bool)Model.Utente.isEnabled))   @MyHelper.decodeAttivaImage(Request.ApplicationPath,(bool)Model.Utente.isEnabled)</div>
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.Utente.email)</div>
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.Utente.dateAdded)</div>
        <div class="ui-bar ui-body-a">@Model.Utente.loginSuccess </div>
        <div class="ui-bar ui-body-a">@Model.Utente.loginFailed</div>
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.Utente.dateLastLogin)</div>
    </div>
</div>

<br />
<h2>Gruppi</h2>
<hr />
@if (Model.Utente.Gruppi == null || Model.Utente.Gruppi.Count == 0)
{
    <h3>Nessun gruppo configurato</h3>
}
else
{
    <ol data-role="listview" data-inset="true">
        @foreach (MyUsers.Models.MyGroup g in Model.Utente.Gruppi)
        {
            <li ><a   href="@Url.Action("Details", "Groups", new {  id = g.gruppoId}) ">@(g.nome)</a></li>
        }
    </ol>
}



<div data-role="controlgrup" data-type="horizontal">
    <a href="@Url.Action("Index", "Utenti")" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Annulla</a>
    <a href="@Url.Action("Edit", "Utenti", new { id = Model.Utente.userId })" class="ui-btn ui-icon-edit ui-btn-icon-left ui-btn-inline ui-corner-all ui-mini">Modifica</a>
    <a href="#" class="ui-btn ui-icon-delete ui-btn-icon-left ui-btn-inline ui-corner-all ui-mini">Elimina</a>
</div>

MediatoriV2/Views/Utenti/Edit.cshtml
@model  MyWebApplication.Areas.Admin.Models.MyUserModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}


<style type="text/css">
    /* Custom indentations are needed because the length of custom labels differs from
            the length of the standard labels */
    .custom-size-flipswitch.ui-flipswitch .ui-btn.ui-flipswitch-on {
        text-indent: -5.9em;
    }

    .custom-size-flipswitch.ui-flipswitch .ui-flipswitch-off {
        text-indent: 0.5em;
    }
    /* Custom widths are needed because the length of custom labels differs from
            the length of the standard labels */
    .custom-size-flipswitch.ui-flipswitch {
        width: 8.875em;
    }

        .custom-size-flipswitch.ui-flipswitch.ui-flipswitch-active {
            padding-left: 7em;
            width: 1.875em;
        }


    .ui-field-contain > label + .custom-size-flipswitch.ui-flipswitch {
        width: 1.875em;
    }
</style>

<script>
    //$(function () {
    //    //per abilitare il controllo anche sui tab hidde
    //    $("form").validate().settings.ignore = "";

    //    //Add custom rule / Validation method
    //    $.validator.addMethod("checkboxrequired", function (value, element, param) {
    //        //alert("checkboxGroup: " + $("[id ^='Gruppi']:checked").length);
    //        if ($("[id ^='Gruppi']").length == 0) {
    //            return false;
    //        }
    //        return true;
    //    }, "Selezionare almeno un gruppo");


    //    $.validator.addClassRules("checkRequireOne", { checkboxrequired: true });
    //    //alert("dd");

    //});
</script>


<h2>Utente: @Model.Utente.login (id: @Model.Utente.userId)</h2>


@using (Html.BeginForm("Edit", "Utenti", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)

    <input type="hidden" name="Utente.userId" value="@Model.Utente.userId" />


    <div class="ui-field-contain">
        <label for="Utente_isEnabled">Stato:</label>
        <input data-role="flipswitch" name="Utente.isEnabled" id="Utente_isEnabled" @(Model.Utente.isEnabled == true ? "checked=checked" : "") data-on-text="Attivo" data-mini="true" value="true" data-off-text="Non attivo" data-wrapper-class="custom-label-flipswitch custom-size-flipswitch" type="checkbox">
    </div>


    <div class="ui-field-contain">
        <label for="email">Email:</label>
        <input type="text" id="email" name="Utente.email" data-clear-btn="true" value="@Model.Utente.email" />
    </div>


    <div class="ui-field-contain">
        <label for="select-profilo">Profilo:</label>
        <select name="ProfiloId" id="select-profilo">
            <option value="">---</option>
            @foreach (SelectListItem i in Model.Profilo)
            {
                <option value="@(i.Value)" @( i.Selected ? "selected" : "")>@(i.Text)</option>
            }
        </select>
    </div>



    <div class="ui-field-contain">
        <fieldset data-role="controlgroup">
            <legend>Gruppi di lavorazine</legend>

            @{
            int conta = 0;
            bool selected;
            }
            @foreach (MyUsers.Models.MyGroup g in Model.Gruppi)
            {

                selected = Model.Utente.Gruppi.Find(x => x.gruppoId == g.gruppoId) != null;

                <input type="checkbox" name="gruppiIDs" id="Gruppi[@(conta)].gruppoId" @( selected ? "checked" : "") value="@(g.gruppoId)" />
                <label for="Gruppi[@(conta++)].gruppoId">@(g.nome) @((!String.IsNullOrEmpty(g.tipo)) ? " [" + g.tipo + "]" : "")</label>
            }

        </fieldset>
    </div>


    <div data-role="controlgrup" data-type="horizontal">
        <a href="@Url.Action("Index", "Utenti")" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Torna alla lista</a>
        <a href="@Url.Action("Details", "Utenti", new { id = Model.Utente.userId })" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Annulla</a>
        <input type="submit" value="Salva" data-inline="true" data-mini="true" />
    </div>

}

MediatoriV2/Views/Utenti/Index.cshtml
@model MyUsers.Models.SearchUsers
@{
    ViewBag.Title = "Elenco utenti";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";

    WebGrid wGrid = new WebGrid(null, rowsPerPage: Model.PageSize, defaultSort: "MY_LOGIN", canPage: false);
    wGrid.Bind(Model.Utenti, rowCount: Model.TotalRows, autoSortAndPage: false);
}

<h2>Elenco utenti</h2>
<a href="@Url.Action("Register", "Utenti")" data-icon="plus" data-inline="true" data-mini="true" data-role="button">Crea un nuovo utente</a>

@using (Html.BeginForm("Index", "Utenti", FormMethod.Post, new { id = "MyForm" }))
{

    <fieldset>
        <legend>Ricerca utenti</legend>
        <table>
            <tr>
                <td>Login</td>
                <td>
                    <input type="text" data-mini="true" data-clear-btn="true" id="filter_login" name="filter.login" value="@Model.filter.login" />
                </td>
                <td>Email</td>
                <td>
                    <input type="text" data-mini="true" data-clear-btn="true" id="filter_email" name="filter.email" value="@Model.filter.email" />
                </td>
            </tr>
            <tr>
                <td>Nome</td>
                <td>
                    <input type="text" data-mini="true" data-clear-btn="true" id="filter_nome" name="filter.nome" value="@Model.filter.nome" />
                </td>
                <td>Cognome</td>
                <td>
                    <input type="text" data-mini="true" data-clear-btn="true" id="filter_cognome" name="filter.cognome" value="@Model.filter.cognome" />
                </td>
            </tr>
        </table>
        <input type="submit" value="Ricerca" data-inline="true" data-icon="search" data-mini="true" />
    </fieldset>


    if (Model.TotalRows == 0)
    {
        <h3>Non è stato trovato nessun utente. Modificare i filtri di ricerca.</h3>
    }
    else
    {
        <div style="margin-top: 20px;">
            @wGrid.GetHtml(
            fillEmptyRows: false,
            tableStyle: MyConstants.TABLE_STYLE,
            headerStyle: MyConstants.TABLE_HEADER_STYLE,
            footerStyle: MyConstants.TABLE_FOOTER_STYLE,
            rowStyle: MyConstants.TABLE_ROW_STYLE,
            alternatingRowStyle: MyConstants.TABLE_ALTERNATING_ROW_STYLE,
            htmlAttributes: new { data_role = "table", id = "MyWebGrid", data_mode = "reflow" },
            columns: new[]{
                wGrid.Column ("Login","login", canSort:true),
                wGrid.Column ("", header: "Profilo" , format: p =>(p.Profili == null || p.Profili.Count== 0?"N/A":p.Profili[0].nome), canSort:true),
                wGrid.Column ("", header: "Gruppi #" , format: p =>(p.Gruppi == null ?"0":p.Gruppi.Count), canSort:true),
                wGrid.Column ("Nome","", canSort  : true),
                wGrid.Column ("Cognome","", canSort  : true),
                wGrid.Column ("Email",  format: @<a href="mailto:@item.Email">@item.Email</a>),
                wGrid.Column (columnName:"isEnabled", header :"Attivo", format: p=> MyHelper.decodeAttivaImage(Request.ApplicationPath,p.isEnabled)),
                wGrid.Column ("DateAdded","Data inserimento", canSort  : true),
                wGrid.Column ("DateLastLogin","Data ultimo accesso", format: p => (p.dateLastLogin == DateTime.MinValue )?" ":p.dateLastLogin  , canSort  : true ),
                wGrid.Column ("", header :"Actions",
                format:@<text>
                    <a class="ui-btn-inline ui-btn ui-icon-info ui-btn-icon-notext ui-corner-all" title="Detail" href="@Url.Action("Details", "Utenti", new { id = item.userId })">Info</a>
                    <a class="ui-btn-inline ui-btn ui-icon-edit ui-btn-icon-notext ui-corner-all" title="Edit" href="@Url.Action("Edit", "Utenti", new { id = item.userId })">Edit</a>
                    <a class="ui-btn-inline ui-btn ui-icon-delete ui-btn-icon-notext ui-corner-all" title="Delete" href="@Url.Action("Delete", "Utenti", new { id = item.userId })">Delete</a>
                </text>, canSort : false)
            })

            @{Html.RenderPartial("Paging", Model);}
        </div>
    }

}

MediatoriV2/Views/Utenti/Register.cshtml
@model mediatori.Models.RegisterModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";

    bool selected;
}

<h2>Register</h2>

<div style="max-width:700px;">
    @using (Html.BeginForm("Register", "Utenti", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <fieldset>
            <legend>Form di registrazione</legend>

            <div class="ui-field-contain">
                <label for="UserName">Email / Login</label>
                <input type="email" name="UserName" id="UserName" data-clear-btn="true" data-mini="true" required value="@Model.UserName" data-val="true" data-val-required="Valore obbligatorio"  data-val-email="Indirizzo email non valido" />
                <span data-valmsg-replace="true" data-valmsg-for="UserName" class="field-validation"></span>
            </div>

            <div class="ui-field-contain">
                <label for="Password">Nuova password:</label>
                <input type="password" name="Password" id="Password" data-clear-btn="true" data-mini="true" required value="@Model.Password" data-val="true"  data-val-required="Valore obbligatorio">
                <span data-valmsg-replace="true" data-valmsg-for="Password" class="field-validation"></span>
            </div>

            <div class="ui-field-contain">
                <label for="ConfirmPassword">Conferma la nuova password:</label>
                <input type="password" name="ConfirmPassword" id="ConfirmPassword" data-clear-btn="true" data-mini="true" required value="@Model.ConfirmPassword" data-val="true" data-val-equalto="La password di conferma non corrisponde" data-val-equalto-other="Password" data-val-required="Valore obbligatorio">
                <span data-valmsg-replace="true" data-valmsg-for="ConfirmPassword" class="field-validation"></span>
            </div>



            <div class="ui-field-contain">
                <label for="select-profilo">Profilo:</label>
                <select name="roles" id="select-profilo" required data-val="true" data-val-required="Valore obbligatorio">
                    <option value="">---</option>
                    @foreach (MyUsers.Models.MyProfile p in Model.ProfiliDisponibili)
                    {
                        selected = false;
                        if (Model.roles != null && p.profiloId == Model.roles[0])
                        {
                            selected = true;
                        }

                        <option value="@p.profiloId" @(selected ? "selected = selected" : "")>@(p.nome)</option>
                    }
                </select>
                <span data-valmsg-replace="true" data-valmsg-for="roles" class="field-validation"></span>
            </div>


            <div data-role="controlgrup" data-type="horizontal">
                <a href="@Url.Action("Sicurezza", "Home")" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Annulla</a>
                <input type="submit" data-inline="true" value="Registrazione" data-mini="true" />
            </div>
        </fieldset>
    }
</div>

MediatoriV2/Views/Utenti/TabInfoAccount.cshtml
@model MyUsers.Models.MyUser

<div class="ui-grid-a">
    <div class="ui-block-a">
        <div class="ui-bar ui-bar-c">Login:</div>
        <div class="ui-bar ui-bar-c">Nome:</div>
        <div class="ui-bar ui-bar-c">Cognome:</div>
        <div class="ui-bar ui-bar-c">Email:</div>
        <div class="ui-bar ui-bar-c">Profilo:</div>
        <div class="ui-bar ui-bar-c">Attivo:</div>
    </div>
    <div class="ui-block-b">
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.login)</div>
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.nome)</div>
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.cognome)</div>
        <div class="ui-bar ui-body-a">
            @if (String.IsNullOrEmpty(Model.email))
            {
                @:N/A
            }
            else
            {
                <a data-role="none"  href="mailto:@Model.email">@Model.email</a>
            }
        </div>
        <div class="ui-bar ui-body-a">
            @{
                string temp;

                if (Model.Profilo == null)
                {
                    temp = "N/A";
                }
                else
                {
                    temp = Model.Profilo.nome;
                }
            }
            @temp
        </div>
        <div class="ui-bar ui-body-a">@Model.isEnabled.ToString()</div>
    </div>
</div>


@if (Model.SID != null)
{
    <br />
    <div class="ui-grid-a">
        <div class="ui-block-a">
            <div class="ui-bar ui-bar-c">SID:</div>
        </div>
        <div class="ui-block-b">
            <div class="ui-bar ui-body-a"><a href="@Url.Action("SID", "Users", new { sid = Model.SID.ToString() })" data-role="none">@(Model.SID.ToString())</a></div>
        </div>
    </div>
}