MediatoriV2/Controllers/NotaController.cs
using mediatori.Controllers.Business;
using mediatori.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mediatori.Controllers
{
    public class NotaController : MyBaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult notaPartial(Nota nota, EnumTipoAzione tipoAzione = EnumTipoAzione.MODIFICA)
        {

            switch (tipoAzione)
            {
                case EnumTipoAzione.MODIFICA:
                    return View("NotaPartialEdit", nota);
                case EnumTipoAzione.INSERIMENTO:
                    return View("NotaPartialInsert", nota);
                default:
                    return View("NotaPartialDetail", nota);
            }
        }

        [ChildActionOnly]
        public ActionResult Create(Nota nota)
        {

#if DEBUG
            //impiego.azienda = "Azienda";
            //impiego.aziendaSedeLavoro = "Sede lavoro";
            ////impiego.dataAssunzione = new DateTime(2000, 8, 1);
            //impiego.mansione = "Impiegato";
            //impiego.mensilita = 14;
            //impiego.stipendioLordoAnnuo = 20000;
            //impiego.stipendioLordoMensile = 1200;
            //impiego.stipendioNettoMensile = 900;
#endif

            ViewData.TemplateInfo.HtmlFieldPrefix = "nota";

            return View("NotaPartialEdit", nota);
        }


        [HttpPost]
        public ActionResult CreateForSegnalazione(Nota nota, int codiceSegnalazione)
        {
            nota = new NotaBusiness().valorizzaDatiDefault(nota, User.Identity.Name);
            ModelState.Clear();
            TryValidateModel(nota);
            if (ModelState.IsValid)
            {
                nota = NotaBusiness.createBySegnalazione(User.Identity.Name, codiceSegnalazione, nota, db);
            }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        [HttpPost]
        public ActionResult CreateForSoggettoGiuridico(Nota nota, int codiceSoggettoGiuridico)
        {
            nota = new NotaBusiness().valorizzaDatiDefault(nota, User.Identity.Name);
            ModelState.Clear();
            TryValidateModel(nota);
            if (ModelState.IsValid)
            {
                nota = NotaBusiness.createBySoggettoGiuridico(User.Identity.Name, codiceSoggettoGiuridico, nota, db);
            }
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

    }
}

MediatoriV2/Views/Nota/NotaPartialDetail.cshtml
@model mediatori.Models.Nota
@{
    Layout = null;
}

<div>
    <div class="display-control">
        @Html.LabelFor(n => n.dataInserimento)
        <div>@Html.DisplayFor(n => n.dataInserimento)</div>
    </div>
    <div class="display-control">
        @Html.LabelFor(n => n.operatoreInserimento)
        <div>@Html.DisplayFor(n => n.operatoreInserimento)</div>
    </div>
    <div class="display-control">
        @Html.LabelFor(m => m.valore)
        <div>@Html.DisplayFor(m => m.valore)</div>
    </div>
</div>

MediatoriV2/Views/Nota/NotaPartialEdit.cshtml
@model mediatori.Models.Nota
@{
    Layout = null;
}

@Html.HiddenFor(m => m.id)

<div class="editor-label">
    @Html.LabelFor(m => m.valore)
    <textarea name="valore" id="valore" rows="3" style="width:100%;"></textarea>
    @Html.ValidationMessageFor(m => m.valore)
</div>

MediatoriV2/Views/Nota/NotaPartialInsert.cshtml
@model mediatori.Models.Nota
@{
    Layout = null;
}


@using(Html.BeginCollectionItem("note")) {
    Html.RenderPartial("NotaPartialEdit");
 }

MediatoriV2/Views/Nota/_Note.cshtml
@model mediatori.Models.NoteModel
@{
    Layout = null;

    string actionName = "";

    if (Model.segnalazioneId != null)
    {
        actionName = "CreateForSegnalazione";
    }
    else if (Model.soggettoGiuridicoId != null)
    {
        actionName = "CreateForSoggettoGiuridico";
    }
}


<script type="text/javascript">
    $(document).on("pageinit", function () {
        $("#linkNuovaNota").click(function () {
            $("#divNuovaNota").show();
        })
    });
</script>


<h3>Note <strong class="h3Link" id="linkNuovaNota" title="Aggiungi Nota">[ + ]</strong></h3>
<hr />

<div id="divNuovaNota" style="display: none">
    @using (Html.BeginForm(actionName, "Nota", FormMethod.Post))
    {
        <input type="hidden" name="codiceSegnalazione" value="@Model.segnalazioneId" />
        <input type="hidden" name="codiceSoggettoGiuridico" value="@Model.soggettoGiuridicoId" />

        { Html.RenderPartial("~/Views/Nota/NotaPartialEdit.cshtml", new mediatori.Models.Nota()); }

        <div data-role="controlgrup" data-type="horizontal">
            <input data-mini="true" data-inline="true" type="submit" value="Salva" />
            <input data-mini="true" data-inline="true" type="button" value="Annulla" onclick='$("#divNuovaNota").hide()' />
        </div>
    }
</div>


@if (Model.note != null)
{
    foreach (mediatori.Models.Nota nota in Model.note)
    {
        {
            Html.RenderPartial("~/Views/Nota/NotaPartialDetail.cshtml", nota);
        }
    }
}