MediatoriV2/Controllers/BlobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;

namespace mediatori.Controllers
{
    public class BlobController : MyBaseController
    {


        private Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer getAzureContainer()
        {


            Microsoft.WindowsAzure.Storage.CloudStorageAccount storageAccount = Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(System.Configuration.ConfigurationManager.ConnectionStrings["AzureStorageConnection"].ConnectionString);

            Microsoft.WindowsAzure.Storage.Blob.CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            // Retrieve a reference to a container. 
            Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer container = blobClient.GetContainerReference("mycontainer");

            return container;

        }


        [HttpPost]
        public JsonResult Add(HttpPostedFileBase MyFile)
        {
            Debug.WriteLine("Add Blog: " + Request["MyFile"]);

            Models.JsonMessageModel model = new Models.JsonMessageModel();

            if (MyFile == null)
            {
                model.esito = Models.JsonMessageModel.Esito.Failed;
                model.messaggio = "Selezionare un file";
                return Json(model);
            }

            Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer container = getAzureContainer();

            // Create the container if it doesn't already exist.
            container.CreateIfNotExists();

            Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blockBlob = container.GetBlockBlobReference(MyFile.FileName);

            try
            {
                blockBlob.UploadFromStream(MyFile.InputStream);
            }
            finally
            {
                MyFile.InputStream.Close();
            }


            model.esito = Models.JsonMessageModel.Esito.Succes;
            model.messaggio = "Operazione conlusa con successo";
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        public JsonResult Delete(string id)
        {
            Debug.WriteLine("Blob: " + id);
            Models.JsonMessageModel model = new Models.JsonMessageModel();


            Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer container = getAzureContainer();
            Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blockBlob = container.GetBlockBlobReference(id);
            if (blockBlob == null)
            {
                model.esito = Models.JsonMessageModel.Esito.Failed;
                model.messaggio = "Selezionare un file";
                return Json(model);
            }

            blockBlob.Delete();

            model.esito = Models.JsonMessageModel.Esito.Succes;
            model.messaggio = "Operazione conlusa con successo";
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Download(string id)
        {
            Debug.WriteLine("Blob: " + id);

            Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer container = getAzureContainer();
            Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blockBlob = container.GetBlockBlobReference(id);
            if (blockBlob == null)
            {
                return HttpNotFound();
            }

            Response.AddHeader("Content-Disposition", "attachment; filename=" + blockBlob.Name); // force download
            Response.AddHeader("Content-Type", System.Web.MimeMapping.GetMimeMapping(blockBlob.Name));
            blockBlob.DownloadToStream(Response.OutputStream);
            return new EmptyResult();
        }



    }
}

MediatoriV2/Views/Shared/Paging.cshtml
<div class="ui-bar-b" style="min-height: 3em;">

    <span style="margin-left: 10px; margin-top: 15px; display: inline-block;">Record @(((Model.PageNumber - 1) * Model.PageSize) + 1) to    
        
    @{
        int temp = (((Model.PageNumber - 1) * Model.PageSize) + Model.PageSize);

        if (temp > Model.TotalRows)
        {
            temp = Model.TotalRows;
        }
            
    }
        @temp.ToString("N0")  of @Model.TotalRows.ToString("N0")

    </span>

    <span style="margin-left: 20px">
        @if (Model.HasPreviousPage)
        {
            <a class="ui-btn ui-btn-inline ui-corner-all ui-mini" href ="javascript:paging(1, '@Model.Sort', '@Model.SortDir')"><< First</a>
            @Html.Raw(" ");
            <a class="ui-btn ui-btn-inline ui-corner-all ui-mini" href ="javascript:paging(@(Model.PageNumber - 1), '@Model.Sort', '@Model.SortDir')">< Prev</a>
        }
        else
        {
            @:<< First
            @Html.Raw(" ");
            @:< Prev
        }
    </span>

    <span style="margin-left: 20px">
        @Html.Raw("Page " + Model.PageNumber.ToString("N0") + " of " + Model.TotalPages.ToString("N0"))
    </span>



    <span style="margin-left: 20px">
        @if (Model.HasNextPage)
        {
            <a class="ui-btn ui-btn-inline ui-corner-all ui-mini" href ="javascript:paging(@(Model.PageNumber + 1), '@Model.Sort', '@Model.SortDir')">Next ></a>
            @Html.Raw(" ");
            <a class="ui-btn ui-btn-inline ui-corner-all ui-mini" href ="javascript:paging(@(Model.TotalPages), '@Model.Sort', '@Model.SortDir')">Last >></a>
        }
        else
        {
            @:Next >
            @Html.Raw(" ")
            @:Last >>
        }
    </span>

    <span style="float: right; text-align: right; display: inline-block; white-space: nowrap; margin-top: 10px; margin-right: 10px;">Page size:
        <select data-inline="true" data-mini="true" data-role="none" id="PageSize" name="PageSize" onchange="paging(1, '@Model.Sort', '@Model.SortDir')">
            <option value="5"  @(Model.PageSize == 5 ? "selected=\"selected\"" : "") >5</option>
            <option value="10" @(Model.PageSize == 10 ? "selected=\"selected\"" : "") >10</option>
            <option value="20" @(Model.PageSize == 20 ? "selected=\"selected\"" : "") >20</option>
            <option value="50" @(Model.PageSize == 50 ? "selected=\"selected\"" : "") >50</option>
        </select>
    </span>
</div>



<script type="text/javascript">

    $(document).on("pagebeforecreate", function () {
        //alert("pagebeforecreate");

        //rutigliano 02/04/2014 per la visualizzazione delle tabelle al 100%
        $("#MyWebGrid").css("display", "table");


        var links = $('#MyWebGrid thead a[href*=sort]');
        //alert(links.length);

        links.click(function () {
            //alert("Click:  " + this.href );
            var pageNumber = $("input[name='PageNumber']").val();
            //alert("PageNumber : " + pageNumber);

            var sort = this.href.match('sort=([a-zA-Z]*)')[1];
            //alert("Sort: " + sort );

            var sortDir = this.href.match('sortdir=([a-zA-Z]*)')[1];
            //alert("SortDir: " + sortDir);

            paging(pageNumber, sort, sortDir);

            return false;
        });




        var tableHeader = $('#MyWebGrid');
        var spanTag = document.createElement("h2");
        //spanTag.id = "span1";
        //spanTag.className = "dynamicSpan";
        spanTag.className = "ui-bar ui-bar-a ui-corner-all ui-mini";
        spanTag.innerHTML = "Record # @String.Format("{0:N0}", Model.TotalRows)";

        tableHeader[0].parentNode.insertBefore(spanTag, tableHeader[0]);

    });



    function paging(page, sort, sortDir) {
        //alert("Paging Sort: " + sort + " " + sortDir);
        //alert("Paging Page Numeber: " + page);

        var pageSize;
        pageSize = $("select[name='PageSize']").val();
        //alert("PageSize: " +  pageSize);

        if ($("input[name='PageNumber']").length == 0) {
            $('<input />').attr('type', 'hidden')
                         .attr('name', 'PageNumber')
                         .attr('value', page)
                         .appendTo('#MyForm');
        } else {
            $("input[name='PageNumber']").val(page);
        }


        if ($("input[name='Sort']").length == 0) {
            $('<input />').attr('type', 'hidden')
                         .attr('name', 'Sort')
                         .attr('value', sort)
                         .appendTo('#MyForm');
        } else {
            $("input[name='Sort']").val(sort);
        }


        if ($("input[name='SortDir']").length == 0) {
            $('<input />').attr('type', 'hidden')
                         .attr('name', 'SortDir')
                         .attr('value', sortDir)
                         .appendTo('#MyForm');
        } else {
            $("input[name='SortDir']").val(sortDir);
        }


        if ($("input[name='PageSize']").length == 0) {
            $('<input />').attr('type', 'hidden')
                         .attr('name', 'PageSize')
                         .attr('value', pageSize)
                         .appendTo('#MyForm');
        } else {
            $("input[name='PageSize']").val(pageSize);
        }

        $("#MyForm").submit();
    }

</script>

MediatoriV2/Views/Shared/_BlobList.cshtml
@model List<Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob> 

<ol data-role="listview" data-inset="true" data-split-icon="delete">
    @foreach (Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blob in Model)
    {
        <li>
            <a href="@Url.Action("Download", "Blob", new { id = blob.Name  })">
                <h2>@blob.Name</h2>
                <p class="ui-li-aside">Size: <strong>@blob.Properties.Length</strong> Data: <strong>@blob.Properties.LastModified.Value.ToString("dd/MM/yyyy")</strong></p>
            </a>

            <a href="javascript:MyAsyncDelete('@blob.Name')">Delete</a>
        </li>
    }
</ol>

MediatoriV2/Views/Shared/_BoxMenu.cshtml
@model List<mediatori.Models.MenuElement>
@{
    Layout = null;
    int conta = 1;

    //style="background-color: rgb(@(87 + 10 * conta), @(158 - 0* conta), @(66 + 0 * conta)  );
}

<div class="canvas-flex">
    @foreach (mediatori.Models.MenuElement configurazione in Model)
    {
        <button id="box_@conta" class="ui-btn ui-btn-d ui-corner-all ui-shadow" style="width:150px; height:150px;white-space: normal;text-overflow:clip;" onclick="javascript:explode( @conta, '@Url.Action(configurazione.action, configurazione.controller)')">@configurazione.display</button>
        conta++;
    }
</div>



<script>
    function explode(indice, url) {
        // alert("explode" + indice);
        //alert(obj.name);

        // $("#Home").hide("explode", {}, 1000);
        //$("#"+obj.name).hide("explode", {}, 1000, function(){
        //alert(obj.name);

        //});

        //for (i = indice; i < @Model.Count; i++) {
        //  $("#box_"+ i).hide("explode", {}, 1000);
        // }

        $("#box_" + indice).hide("explode", {}, 1000);
        location.href = url;


        //$(".SICUREZZA").show("drop", {}, 1000);

    }
</script>

MediatoriV2/Views/Shared/_ComboData.cshtml
@model mediatori.Models.UI.ComboDataModel

<select name="Days" id="Days" data-mini="true" data-inline="true" @(Model.isEnabled?"":"disabled")>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Tutti)"                            @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Tutti) ? "selected" : "")>Tutti</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Oggi)"                             @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Oggi) ? "selected" : "")>Oggi</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Ieri)"                             @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Ieri) ? "selected" : "")>Ieri</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Settimana_corrente)"               @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Settimana_corrente) ? "selected" : "")>Settimana corrente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Settimana_precedente)"             @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Settimana_precedente) ? "selected" : "")>Settimana precedente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Ultimi_7_giorni )"                 @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Ultimi_7_giorni) ? "selected" : "")>Ultimi 7 giorni</option>     
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Mese_corrente)"                    @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Mese_corrente) ? "selected" : "")>Mese corrente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Mese_precedente)"                  @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Mese_precedente) ? "selected" : "")>Mese precedente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Ultimi_30_giorni  )"               @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Ultimi_30_giorni) ? "selected" : "")>Ultimi 30 giorni</option>     
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Primo_semestre_anno_corrente)"     @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Primo_semestre_anno_corrente) ? "selected" : "")>Primo semestre anno corrente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Primo_semestre_anno_precedente)"   @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Primo_semestre_anno_precedente) ? "selected" : "")>Primo semestre anno precedente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Secondo_semestre_anno_corrente)"   @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Secondo_semestre_anno_corrente) ? "selected" : "")>Secondo semestre anno corrente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Secondo_semestre_anno_precedente)" @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Secondo_semestre_anno_precedente) ? "selected" : "")>Secondo semestre anno precedente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Ultimo_semestre)"                  @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Ultimo_semestre) ? "selected" : "")>Ultimo semestre</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Anno_corrente)"                    @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Anno_corrente) ? "selected" : "")>Anno corrente</option>
    <option value="@((int)MyManagerCSharp.ManagerDB.Days.Anno_precedente)"                  @((Model.selectedValue == MyManagerCSharp.ManagerDB.Days.Anno_precedente) ? "selected" : "")>Anno precedente</option>
</select>

MediatoriV2/Views/Shared/_ComboNumeroRate.cshtml
@model Nullable<int>

@{
    int? numeroRate;
    if (Model == null)
    {
        numeroRate = null;
    }
    else
    {
        numeroRate = Model.Value;
    }
}

<select name="numeroRate" id="numeroRate" data-mini="true" data-inline="true">
    <option value=""   @((numeroRate == null || numeroRate == -1) ? "selected" : "")>---</option>
    <option value="12" @((numeroRate == 12) ? "selected" : "")>12</option>
    <option value="24" @((numeroRate == 24) ? "selected" : "")>24</option>
    <option value="36" @((numeroRate == 36) ? "selected" : "")>36</option>
    <option value="48" @((numeroRate == 48) ? "selected" : "")>48</option>
    <option value="60" @((numeroRate == 60) ? "selected" : "")>60</option>
    <option value="72" @((numeroRate == 72) ? "selected" : "")>72</option>
    <option value="84" @((numeroRate == 84) ? "selected" : "")>84</option>
    <option value="96" @((numeroRate == 96) ? "selected" : "")>96</option>
    <option value="108" @((numeroRate == 108) ? "selected" : "")>108</option>
    <option value="120" @((numeroRate == 120) ? "selected" : "")>120</option>
</select>

MediatoriV2/Views/Shared/_Flipswitch.cshtml
@model mediatori.Models.FlipswitchModel

<input data-role="flipswitch" name="@Model.name" id="@Model.name.Replace(".","_")" @(Model.isChecked == true ? "checked=checked" : "") data-on-text="Attiva" data-mini="true" value="true" data-off-text="Non attiva" data-wrapper-class="custom-label-flipswitch custom-size-flipswitch" type="checkbox">

<style type="text/css">
    /* Custom indentations are needed because the length of custom labels differs from
            the length of the standard labels */
    .custom-size-flipswitch.ui-flipswitch .ui-btn.ui-flipswitch-on {
        text-indent: -5.9em;
    }

    .custom-size-flipswitch.ui-flipswitch .ui-flipswitch-off {
        text-indent: 0.5em;
    }
    /* Custom widths are needed because the length of custom labels differs from
            the length of the standard labels */
    .custom-size-flipswitch.ui-flipswitch {
        width: 8.875em;
    }

        .custom-size-flipswitch.ui-flipswitch.ui-flipswitch-active {
            padding-left: 7em;
            width: 1.875em;
        }


    .ui-field-contain > label + .custom-size-flipswitch.ui-flipswitch {
        width: 1.875em;
    }
</style>

MediatoriV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="it">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />


    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/fireAntUtils")
    @Scripts.Render("~/bundles/scheduler")
    @Styles.Render("~/Content/css/scheduler")



</head>
<script>

   @{ String contesto = Request.ApplicationPath;
      if (contesto == "/")
      {
          contesto = "";
      }
    }

    var contextPath = '@contesto';


    $(function () {
        clock();

        assegnazioni();

        // $("#segnalazioni").hide();

        //setTimeout(function () { assegnazioni(); }, 2000);
    });


    function clock() {
        var d = new Date();
        $("#headerClock").html(d.toLocaleDateString() + " - " + d.toLocaleTimeString());

        setTimeout(function () {
            clock();
        }, 1000);
    }



    var isFirstTime = true;

    function assegnazioni() {
        //alert("assegnazioni");
        $.getJSON('@Url.Action("Assegnazioni", "Home")', function (myresponse) {

            var str = "";
            str = "Da assegnare: " + myresponse[0].Value;
            // $("#segnalazioniDaAssegnare").html(str);

            str = "Assegnate: " + myresponse[1].Value;
            //$("#segnalazioniAssegnate").html(str);
            str = myresponse[0].Value;
            // alert(str);

            if ($("#headerSegnalazioni").html() != str) {

                $("#headerSegnalazioni").html(str);

                if (isFirstTime) {
                    isFirstTime = false;
                } else {
                    $("#headerSegnalazioni").effect("shake");
                }
            }
            // alert(str);
            //$("#segnalazioni").show("slide", 1000)


        });

        setTimeout(function () { assegnazioni(); }, 2000);
    }
</script>

<body>
    <div id="header">
        <a href="@Url.Action("Index", "Home")">
            <div id="headerLogo"></div>
        </a>
        <div id="headerTechub"></div>
        <div id="headerHelp" class=".ui-widget-header .ui-icon .ui-icon-help" title="help"></div>
        <a href="javascript:assegnazioni();" data-role="none" title="Assegnazioni">
            <div id="headerSegnalazioni">
                0
            </div>
        </a>
        <a href="@Url.Action("Assegnazioni", "Home")">
            <div id="headerCalendario"></div>
        </a>
        <div id="headerDatiUtente">
            @if (User.Identity.Name != null)
            {
                @User.Identity.Name
            }
        </div>
        <div id="headerClock"></div>
    </div>
    <!-- /header -->

    <div id="topMenu">
        <div class="topMenuItem" id="topMenuHome">Home</div>
        <div class="topMenuItem" id="topMenuAnagrafica">Anagrafica</div>
        <div class="topMenuItem" id="topMenuSicurezza">Sicurezza</div>
        <div class="topMenuItem" id="topMenuConfigurazioni">Configurazioni</div>
    </div>

    <script>
        $("#topMenuHome").click(function () { window.location = "@Url.Action("Index", "Home")"; });
        $("#topMenuAnagrafica").click(function () { window.location = "@Url.Action("Index", "Home")?s=ANAGRAFICA"; });
        $("#topMenuSicurezza").click(function () { window.location = "@Url.Action("Index", "Home")?s=SICUREZZA"; });
        $("#topMenuConfigurazioni").click(function () { window.location = "@Url.Action("Index", "Home")?s=CONFIGURAZIONI"; });
        //$("#headerCalendario").click(
        //    function () {
        //        $("#divCalendar").dialog("open");
        //        scheduler.init('calendarioAgendaEventi', new Date(), "month")
        //    });

        $(function () {
            $("#divCalendar").dialog({
                autoOpen: false,
                show: {
                    effect: "blind",
                    duration: 1000
                },
                hide: {
                    effect: "explode",
                    duration: 1000
                }
            });
        });

        function displayError(message) {
            $("#errorMessage").html(message);
            $("#errorMessage").show("slide", 1000);
            $("<div/>", { html: "[X]", id: "divErroButton", style: "float:right;cursor:hand;cursor:pointer", }).appendTo("#errorMessage");
            $("#divErroButton").click(function () { $("#errorMessage").hide("slide", 1000); });
        }

        function displayMessage(message) {
            $("#displayMessage").html(message);
            $("#displayMessage").show("slide", 1000);
            $("<div/>", { html: "[X]", id: "divDisplayButton", style: "float:right;cursor:hand;cursor:pointer", }).appendTo("#displayMessage");
            $("#divDisplayButton").click(function () { $("#displayMessage").hide("slide", 1000); });
        }

    </script>
    <div id="divCalendar" style="display: none">
        <div id="calendarioAgendaEventi" class="dhx_cal_container" style='width: 700px; height: 300px;'>
            <div class="dhx_cal_navline">
                <div class="dhx_cal_prev_button">&nbsp;</div>
                <div class="dhx_cal_next_button">&nbsp;</div>
                <div class="dhx_cal_today_button"></div>
                <div class="dhx_cal_date"></div>
                <div class="dhx_cal_tab" name="day_tab" style="right: 204px;"></div>
                <div class="dhx_cal_tab" name="week_tab" style="right: 140px;"></div>
                <div class="dhx_cal_tab" name="month_tab" style="right: 76px;"></div>
            </div>
            <div class="dhx_cal_header"></div>
            <div class="dhx_cal_data"></div>
        </div>
    </div>


    <table style="width: 90%;">
        <tr>
            @if (User.IsInRole("Amministratore"))
            {
                <td style="vertical-align: top; width: 260px">
                    <div id="secondaryContent">@Html.Partial("_MenuPrincipale")</div>
                </td>
            }
            <td style="vertical-align: top;">
                <div id="primaryContent">
                    <div id="errorMessage" style="display: none"></div>
                    <div id="displayMessage" style="display: none"></div>
                    @RenderBody()
                </div>
            </td>
        </tr>
    </table>

    @RenderSection("scripts", required: false)

    <script>
        $(function () {
            $("input[type=submit], button,input[type=button]").button();

        });
    </script>
</body>
</html>

MediatoriV2/Views/Shared/_PopupConfirmDelete.cshtml
@model mediatori.Models.PopupConfirmDeleteModel

<div data-role="popup" id="popupConfirmDelete" data-overlay-theme="b" data-theme="a" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Cancellazione?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Confermare l'operazione di cancellazione?</h3>
        <p>Questa operazione è irreversibile.</p>

        @using (Html.BeginForm(Model.actionName, Model.controllerName, FormMethod.Post, null))
        {
            @Html.AntiForgeryToken()

            foreach (mediatori.Models.HiddenFiled field in Model.hiddenFields)
            {
                @Html.Raw(field.ToString());
            }

            <div data-role="controlgrup" data-type="horizontal">
                <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b ui-mini" data-rel="back">Annulla</a>
                <input type="submit" value="Elimina" data-inline="true" data-mini="true" data-icon="delete" />
            </div>
        }
    </div>
</div>

MediatoriV2/Views/Shared/_ProvinciaComune.cshtml
@model mediatori.Models.Anagrafiche.Indirizzo


<div class="editor-label">
    <label for="provincia">Provincia</label>
    <select name="provincia" id="provincia" data-mini="true" data-val-required="Selezionare la provincia">
        <option value="">---</option>
        @foreach (SelectListItem i in ViewBag.listaProvincia)
        {
            <option value="@i.Value" @((i.Selected) ? "selected" : "")>@i.Text</option>
        }
    </select>

    <span class="field-validation-valid" data-valmsg-for="provincia" data-valmsg-replace="true"></span>

</div>

<div class="editor-label">
    <label for="comune">Comune</label>
    <select name="comune" id="comune" data-mini="true" data-val-required="Selezionare il comune">
        <option value="">Selezionare una Provincia ...</option>
    </select>
    <span class="field-validation-valid" data-valmsg-for="comune" data-valmsg-replace="true"></span>
</div>


<script type="text/javascript">
    $(document).on("pageinit", function () {
        $("#provincia").change(function () {
            //   alert("provincia CHANGE");
            popolaComboComuni("provincia", "comune");
        });
    });
</script>