MediatoriV2/Areas/Admin/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using MyUsers;


namespace MyWebApplication.Areas.Admin.Controllers
{

    [MyAuthorize(Roles = "ADMIN")]
    public class GroupsController : MyBaseController
    {
        private GroupManager manager = new GroupManager("utenti");

        public ActionResult Index(MyUsers.Models.SearchGroups model)
        {
            

            manager.openConnection();
            try
            {
                 manager.getList(model);

                foreach (MyUsers.Models.MyGroup g in model.Gruppi )
                {
                    g.countUsers = manager.countUsers(g.gruppoId);
                    g.countRoles = manager.countRoles(g.gruppoId);
                }


                model.ListaTipi = manager.getTypeList(); 

            }
            finally
            {
                manager.closeConnection();
            }

          

            return View(model);
        }


        public ActionResult Create()
        {
            Models.MyGroupModel model = new Models.MyGroupModel();
            model.Gruppo = new MyUsers.Models.MyGroup();

            populateComboBox(model.Gruppo);

            return View(model);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.MyGroupModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Gruppo == null)
                {
                    //group = new MyUsers.Models.MyGroup();
                    //TryUpdateModel(group);
                }

                manager.openConnection();
                try
                {
                    manager.insert(model.Gruppo);
                }
                finally
                {
                    manager.closeConnection();
                }

                return RedirectToAction("Index");
            }

            populateComboBox(model.Gruppo);
            return View(model);
        }

        public ActionResult Delete(int id = 0)
        {
            Models.MyGroupModel model = new Models.MyGroupModel();
            manager.openConnection();
            try
            {
                model.Gruppo = manager.getGroup(id);
                if (model.Gruppo == null)
                {
                    return HttpNotFound();
                }


                if (model.Gruppo.nome.ToUpper() == "GUEST" )
                {
                    ModelState.AddModelError(string.Empty , "Non è possibile cancellare il gruppo di sistema 'Guest'");
                }

                if (model.Gruppo.nome.ToUpper() == "ADMINISTRATORS")
                {
                    ModelState.AddModelError(string.Empty, "Non è possibile cancellare il gruppo di sistema 'Administrators'");
                }
            }
            finally
            {
                manager.closeConnection();
            }
            return View(model);
        }



        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            manager.openConnection();
            try
            {
                manager.delete((long)id);
            }
            finally
            {
                manager.closeConnection();
            }

            return RedirectToAction("Index");
        }




        public ActionResult Edit(int id = 0)
        {
            Models.MyGroupModel model = new Models.MyGroupModel();
            manager.openConnection();
            try
            {
                model.Gruppo = manager.getGroup(id);
                if (model.Gruppo == null)
                {
                    return HttpNotFound();
                }

                manager.setRoles(model.Gruppo);
                model.Utenti = manager.getUsers(model.Gruppo.gruppoId);

                model.ListaTipi = manager.getTypeList(); 

                GroupManager groupManager = new GroupManager(manager.getConnection());
                if (model.Gruppo.Ruoli != null)
                {
                    model.Ruoli = new MultiSelectList(groupManager.getRoleList(), "ruoloId", "nome", model.Gruppo.Ruoli.Select(x => x.ruoloId).ToArray());
                }
                else
                {
                    model.Ruoli = new MultiSelectList(groupManager.getRoleList(), "ruoloId", "nome", null);
                }

                //populateComboBox(group);
            }
            finally
            {
                manager.closeConnection();
            }



            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.MyGroupModel model)
        {
            if (ModelState.IsValid)
            {
                //TryUpdateModel(group);  

                manager.openConnection();
                try
                {
                    manager.update(model.Gruppo);
                }
                finally
                {
                    manager.closeConnection();
                }

                return RedirectToAction("Index");
            }

            model.Utenti = manager.getUsers(model.Gruppo.gruppoId);

            GroupManager groupManager = new GroupManager(manager.getConnection());

            if (model.Gruppo.Ruoli != null)
            {
                model.Ruoli = new MultiSelectList(groupManager.getRoleList(), "ruoloId", "nome", model.Gruppo.Ruoli.Select(x => x.ruoloId).ToArray());
            }
            else
            {
                model.Ruoli = new MultiSelectList(groupManager.getRoleList(), "ruoloId", "nome", null);
            }
            model.ListaTipi = manager.getTypeList(); 
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Roles(Models.MyGroupModel model)
        {

            string permessiSelected = Request.Form["permessiIDs"];
            Debug.WriteLine("permessiIDs: " + permessiSelected);

            Debug.WriteLine("GruppoId: " + model.Gruppo.gruppoId);


            //if (String.IsNullOrEmpty(permessiSelected))
            //{
            //    ModelState.AddModelError(string.Empty, "Occorre selezionare almeno un permersso");
            //}


            if (ModelState.IsValid)
            {
                List<MyUsers.Models.MyRole> lista = new List<MyUsers.Models.MyRole>();

                if (permessiSelected != null)
                {
                    foreach (string id in permessiSelected.Split(','))
                    {
                        lista.Add(new MyUsers.Models.MyRole(id));
                    }

                }
                model.Gruppo.Ruoli = lista;


                manager.openConnection();
                try
                {
                    manager.updateRuoli(model.Gruppo);
                }
                finally
                {
                    manager.closeConnection();
                }

                //return RedirectToAction("Details", new { id = model.Gruppo.gruppoId });
                return new RedirectResult(Url.Action("Details", new { id = model.Gruppo.gruppoId }) + "#tabs-3");
            }

            populateComboBox(model.Gruppo);
            return View("Edit", model);
        }




        public ActionResult Details(long id = 0)
        {
            Models.MyGroupModel model = new Models.MyGroupModel();
            manager.openConnection();
            try
            {
                model.Gruppo = manager.getGroup(id);

                if (model.Gruppo == null)
                {
                    return HttpNotFound();
                }

                manager.setRoles(model.Gruppo);
                model.Utenti = manager.getUsers(model.Gruppo.gruppoId);
            }
            finally
            {
                manager.closeConnection();
            }
            return View(model);
        }



        public ActionResult Users(long id = 0)
        {
            List<MyUsers.Models.MyUser> lista;

            lista = manager.getUsers(id);


            return PartialView("listaUtenti", lista);
        }




        private void populateComboBox(MyUsers.Models.MyGroup group)
        {
            List<MyUsers.Models.MyRole> listaPermessi;
            manager.openConnection();
            try
            {
                listaPermessi = manager.getRoleList();


                MultiSelectList msl;
                if (group != null && group.Ruoli != null)
                {
                    msl = new MultiSelectList(listaPermessi, "permessoId", "nome", group.Ruoli.Select(x => x.ruoloId).ToArray());
                }
                else
                {
                    msl = new MultiSelectList(listaPermessi, "permessoId", "nome", null);
                }

                ViewBag.Permessi = msl;

            }
            finally
            {
                manager.closeConnection();
            }




        }


        public ActionResult SearchAD()
        {
            Debug.WriteLine("Search in Active Directory");


            MyUsers.LdapManager managerAD = new MyUsers.LdapManager(System.Configuration.ConfigurationManager.AppSettings["ldap.server"], System.Configuration.ConfigurationManager.AppSettings["ldap.login"], System.Configuration.ConfigurationManager.AppSettings["ldap.password"], System.Configuration.ConfigurationManager.AppSettings["ldap.container"]);
            managerAD.getGroups();


            return View();
        }





        public ActionResult SearchUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUser(long gruppoId)
        {
            Debug.WriteLine("gruppoId: " + gruppoId);

MediatoriV2/Views/Groups/Create.cshtml
@model MyWebApplication.Areas.Admin.Models.MyGroupModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

<h2>Nuovo gruppo</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    
    <div data-role="fieldcontain">
        <label for="nome">Nome*:</label>
        <input type="text" data-clear-btn="true" name="gruppo.nome" id="nome" data-mini="true" data-inline="true"  required="required"  value="@Model.Gruppo.nome" />
    </div>
    
    <div data-role="controlgrup" data-type="horizontal" data-mini="true">
        <a href="@Url.Action("Index", "Groups")"    data-inline="true" data-mini="true"   data-role="button"  >Annulla</a>
        <input type="submit" value="Crea" data-inline="true" data-mini="true" />
    </div>
    
}

MediatoriV2/Views/Groups/Delete.cshtml
@model MyWebApplication.Areas.Admin.Models.MyGroupModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

<h2>Gruppo: @Model.Gruppo.nome (id: @Model.Gruppo.gruppoId)</h2>


@if (ViewData.ModelState.IsValid)
{
    <p>Confermare la cancellazione del gruppo "@Model.Gruppo.nome"?</p>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary() 
    <input type="hidden" name="id" value ="@Model.Gruppo.gruppoId" />

    <div data-role="controlgrup" data-type="horizontal" data-mini="true">
        <a href="@Url.Action("Index", "Groups")"   data-inline="true"  data-mini="true"  data-role="button"  >Torna alla lista</a>
        <a href="@Url.Action("Details", "Groups", new { id = Model.Gruppo.gruppoId })"   data-mini="true"  data-inline="true"   data-role="button"  >Annulla</a>

        @if (ViewData.ModelState.IsValid)
        {
            <input type="submit" value="Delete" data-mini="true" data-inline="true" />
        }
    </div>
}

MediatoriV2/Views/Groups/DeleteUser.cshtml
@model MyWebApplication.Areas.Admin.Models.MyGroupModel

@{
    ViewBag.Title = "DeleteUser";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}


<h2>Cancellazione utente</h2>

rimuovere l'associazione  tra il gruppo @Model.Gruppo.nome e l'utente @((Model.Utenti as List<MyUsers.Models.MyUser>)[0].login  )?
    


@using (Html.BeginForm("DeleteUser", "Groups", FormMethod.Post, new { id = "MyForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

     <input type="hidden" name="gruppoId" value="@Model.Gruppo.gruppoId " />
    <input type="hidden" name="userId" value="@((Model.Utenti as List<MyUsers.Models.MyUser>)[0].userId) " />
    
    
    <div data-role="controlgrup" data-type="horizontal" data-mini="true">
        <a href="@Url.Action("Edit", "Groups",new { id = Model.Gruppo.gruppoId })#tabs-2"  class="ui-btn-inline ui-btn ui-corner-all ui-mini"   >Annulla</a>
        <input type="submit" value="Elimina" data-inline="true" data-mini="true"  />
    </div>
    
    
}

MediatoriV2/Views/Groups/Details.cshtml
@model MyWebApplication.Areas.Admin.Models.MyGroupModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}
<h2>Gruppo: @Model.Gruppo.nome (id: @Model.Gruppo.gruppoId)</h2>

<div class="ui-grid-a">
    <div class="ui-block-a">
        <div class="ui-bar ui-bar-a">Nome:</div>
    </div>
    <div class="ui-block-b">
        <div class="ui-bar ui-body-a">@MyHelper.decodeNull(Model.Gruppo.nome)</div>
    </div>
</div>



<h2>Utenti</h2>
    @if (Model.Utenti.Count() == 0)
    {
        <h3>Nessun utente associato</h3>
    }
    else
    {
        <ol data-role="listview" data-inset="true">
            @foreach (MyUsers.Models.MyUser u in Model.Utenti)
            {
                <li><a href="@Url.Action("Details", "Utenti", new { id = u.userId })">@(u.login)</a></li>
            }
        </ol>
    }


<div data-role="controlgrup" data-type="horizontal">
    <a href="@Url.Action("Index", "Groups")" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Torna alla lista</a>
    <a href="@Url.Action("Edit", "Groups", new { id = Model.Gruppo.gruppoId })" class="ui-btn ui-icon-edit ui-btn-icon-left ui-btn-inline ui-corner-all ui-mini">Modifica</a>
    <a href="@Url.Action("Delete", "Groups", new { id = Model.Gruppo.gruppoId })" class="ui-btn ui-icon-delete ui-btn-icon-left ui-btn-inline ui-corner-all ui-mini">Elimina</a>
</div>


<script>
    $(function () {
        //alert("ready");

        $("#button").click(function () {
            //  alert("click");
            $.ajax({
                type: "GET",
                url: "/Groups/Users/@Model.Gruppo.gruppoId",
                dataType: "html",
                success: function (resultdata) {
                    $('#usersList').html(resultdata);
                }
            });
        });

    });
</script>

MediatoriV2/Views/Groups/Edit.cshtml
@model  MyWebApplication.Areas.Admin.Models.MyGroupModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}


<h2>Gruppo: @Model.Gruppo.nome (id: @Model.Gruppo.gruppoId)</h2>

@using (Html.BeginForm("Edit", "Groups", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <input type="hidden" name="Gruppo.gruppoId" value="@Model.Gruppo.gruppoId" />

    <div class="ui-field-contain">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="Gruppo.nome" required="required" value="@Model.Gruppo.nome" />
    </div>

    <h2>Utenti</h2>

    <p>Inserisci il nome dell'utente da aggiungere al gruppo:</p>
    <input type="text" id="searchField" data-icon="plus" placeholder="Login utente da cercare">
    <fieldset id="suggestions" data-role="controlgroup">
        <legend></legend>
    </fieldset>

    <br />

    if (Model.Utenti == null || Model.Utenti.Count<MyUsers.Models.MyUser>() == 0)
    {
        <h3>Nessun utente associato</h3>
    }
    else
    {
        <ul data-role="listview" data-inset="true">
            @foreach (MyUsers.Models.MyUser u in Model.Utenti)
            {
                <li data-icon="delete"><a href="@Url.Action("DeleteUser", "Groups", new { id = Model.Gruppo.gruppoId, userId = u.userId })">@u.login</a></li>
            }
        </ul>
    }


    <div data-role="controlgrup" data-type="horizontal">
        <a href="@Url.Action("Index", "Groups")" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Torna alla lista</a>
        <a href="@Url.Action("Details", "Groups", new { id = Model.Gruppo.gruppoId })" class="ui-btn-inline ui-btn ui-corner-all ui-mini">Annulla</a>
        <input type="submit" value="Salva" data-inline="true" data-mini="true" />
    </div>
 
}




<script>
    $(document).on("pageshow", function () {
        // alert("pageshow");

        $("#searchField").on("input", function (e) {
            var text = $(this).val();

            if (text.length < 3) {
                $("#suggestions").html("");
                $("#suggestions").listview("refresh");
            } else {

                console.log("source");
                $.getJSON('@Url.Action("AutoCompleteLogin", "Utenti")', { value: text }, function (mydata) {

                    var str = "";
                    for (var i = 0, len = mydata.length; i < len; i++) {
                        //str += "<li>" + res[i] + "</li>";
                        str += "<input type =\"checkbox\" name=\"myItems\" id=\"myItems[" + i + "]\"  value =\"" + mydata[i].Value + "\">";
                        str += "<label for=\"myItems[" + i + "]\">" + mydata[i].Text + "</label>";

                    }

                    $("#suggestions").html(str);

                    $("[type=checkbox]").checkboxradio();
                    $("[data-role=controlgroup]").controlgroup("refresh");
                });

                //$("#searchField").removeClass('ui-autocomplete-loading');
                console.log("source END");
            }
        });


    });
</script>

MediatoriV2/Views/Groups/Index.cshtml
@model MyUsers.Models.SearchGroups
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
    WebGrid wGrid = new WebGrid(null, rowsPerPage: Model.PageSize, defaultSort: "NOME", canPage: false);
    wGrid.Bind(Model.Gruppi, rowCount: Model.TotalRows, autoSortAndPage: false);

    bool chk;
}

<h2>Configurazione gruppi</h2>
<a href="#popupNuovo" data-rel="popup" data-position-to="window" class="ui-btn ui-corner-all ui-shadow ui-mini ui-btn-inline ui-icon-plus ui-btn-icon-left">Nuovo gruppo</a>


@using (Html.BeginForm("Index", "Groups", FormMethod.Post, new { id = "MyForm" }))
{

    if (Model.ListaTipi != null && Model.ListaTipi.Count > 0)
    {

        <div class="ui-field-contain">
            <label for="filter_tipo">Tipo:</label>
            <select name="filter.tipo" id="filter_tipo" data-mini="true" data-inline="true">
                <option value="" @((String.IsNullOrEmpty(Model.filter.tipo)) ? "selected" : "")>---</option>

                @foreach (MyManagerCSharp.Models.MyItem item in Model.ListaTipi)
                {
                    if (Model.filter.tipo != null && Model.filter.tipo == item.Value)
                    {
                        chk = true;
                    }
                    else
                    {
                        chk = false;
                    }
                    <option value="@item.Value" @((chk) ? "selected" : "")>@item.Text</option>
                }
            </select>
        </div>

    }


    if (Model.TotalRows == 0)
    {
        <h3>Non è stato trovato nessun gruppo.</h3>
    }
    else
    {

        <div style="margin-top: 20px;">
            @wGrid.GetHtml(
            fillEmptyRows: false,
           tableStyle: MyConstants.TABLE_STYLE,
                 headerStyle: MyConstants.TABLE_HEADER_STYLE,
                 footerStyle: MyConstants.TABLE_FOOTER_STYLE,
                 rowStyle: MyConstants.TABLE_ROW_STYLE,
                 alternatingRowStyle: MyConstants.TABLE_ALTERNATING_ROW_STYLE,
            htmlAttributes: new { data_role = "table", id = "MyWebGrid", data_mode = "reflow" },
            columns: new[]{
                wGrid.Column ("Nome","", canSort  : true),
                wGrid.Column ("countUsers","Numero utenti", canSort  : false ),
                wGrid.Column ("", header :"Actions",  format:@<text>
                    <a class="ui-btn-inline ui-btn ui-icon-info ui-btn-icon-notext ui-corner-all" href="@Url.Action("Details", "Groups", new { id = item.gruppoId })">Info</a>
                    <a class="ui-btn-inline ui-btn ui-icon-edit ui-btn-icon-notext ui-corner-all" title="Edit" href="@Url.Action("Edit", "Groups", new { id = item.gruppoId })">Edit</a>
                    <a class="ui-btn-inline ui-btn ui-icon-delete ui-btn-icon-notext ui-corner-all" href="@Url.Action("Delete", "Groups", new { id = item.gruppoId })">Delete</a>
                </text>, canSort : false)
                }
                   )

            @{Html.RenderPartial("Paging", Model);}
        </div>
    }

}


<script type="text/javascript">
    $(document).on("pageinit", function () {

        $("#filter_tipo").change(function () {
            $("#MyForm").submit();
        });

    });

</script>



<div data-role="popup" id="popupNuovo" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="min-width:500px">
    <div data-role="header" data-theme="a">
        <h1>Nuovo gruppo di lavorazione</h1>
    </div>
    <div role="main" class="ui-content">
        <p>Dopo aver creato il gruppo clicca su modifica per aggiungere gli utenti.</p>
        @using (Html.BeginForm("Create", "Groups", FormMethod.Post, null))
        {
            @Html.AntiForgeryToken()
            <div class="ui-field-contain">
                <label for="gruppo_nome">Nome</label>
                <input type="text" name="gruppo.nome" id="gruppo_nome" required />
            </div>

            <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b ui-mini">Annulla</a>
            <input type="submit" value="Conferma" data-inline="true" data-mini="true" />
        }
    </div>
</div>

MediatoriV2/Views/Groups/SearchUser.cshtml
@{
    ViewBag.Title = "SearchUser";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

<h2>SearchUser</h2>


<input type="text" id="searchField" placeholder="Search">

<div>

    <fieldset id="suggestions" data-role="controlgroup">
        <legend></legend>
    </fieldset>

</div>




<script>
    $(document).on("pageshow", function () {
        //alert("pageinit");
        console.log("Ready to bring the awesome.");
        var sugList = $("#suggestions");

        $("#searchField").on("input", function (e) {
            var text = $(this).val();

            if (text.length < 3) {
                sugList.html("");
                sugList.listview("refresh");
            } else {

                //                alert(text);

                $.getJSON('@Url.Action("AutoCompleteLogin", "Users")', { value: text }, function (mydata) {

                    var str = "";

                    for (var i = 0, len = mydata.length; i < len; i++) {
                        //str += "<li>" + res[i] + "</li>";
                        str += "<input type =\"checkbox\" name=\"myItems\" id=\"myItems[" + i + "]\"  value =\"" + mydata[i].Value + "\">";
                        str += "<label for=\"myItems[" + i + "]\">" + mydata[i].Text + "</label>";

                    }


                    sugList.html(str);
                    //sugList.listview("refresh");
                    //$('input:checkbox').checkboxradio('refresh');
                    $("[type=checkbox]").checkboxradio();
                    $("[data-role=controlgroup]").controlgroup("refresh");

                    console.dir(mydata);
                });

            }
        });
    });
</script>